# Generated by Django 3.1.6 on 2021-02-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210208_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/abc.jpg', upload_to='images/'),
        ),
    ]
